---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

  when:
    branch:
    - master
    event:
    - push
    - pull-request
    
trigger:
  branch:
  - master
